#!/bin/bash
set -e

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; BOLD='\033[1m'; NC='\033[0m'

MODE=${MODE:-demo}

echo ""
echo -e "${BOLD}${BLUE}╔══════════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}${BLUE}║   Atomic CRM + Claude Code                           ║${NC}"

if [ "$MODE" = "demo" ]; then
echo -e "${BOLD}${BLUE}║   Mode: DEMO  (FakeRest — no database required)      ║${NC}"
else
echo -e "${BOLD}${BLUE}║   Mode: FULL  (local Supabase)                       ║${NC}"
fi

echo -e "${BOLD}${BLUE}╚══════════════════════════════════════════════════════╝${NC}"
echo ""

# ── Auth check — API key or OAuth token ───────────────────────
CLAUDE_DIR="/home/developer/.claude"
if [ -n "${ANTHROPIC_API_KEY}" ]; then
  echo -e "${GREEN}✓  Auth: API key${NC}"
elif [ -f "${CLAUDE_DIR}/.credentials.json" ] || [ -f "${CLAUDE_DIR}/credentials.json" ]; then
  echo -e "${GREEN}✓  Auth: OAuth token (claude login)${NC}"
else
  echo -e "${YELLOW}⚠️   No authentication found — starting terminal for claude login${NC}"
  echo ""
  echo -e "${BOLD}  → Open http://localhost:7681 in your browser${NC}"
  echo -e "  → Run: ${YELLOW}claude login${NC}"
  echo -e "  → Then restart this container (Ctrl+C, then docker compose up again)"
  echo ""
  export HOME=/home/developer
  exec /usr/local/bin/ttyd --port 7681 --writable --interface 0.0.0.0 /usr/local/bin/ttyd-session.sh
fi

# Always use the image's .claude config (volume may have stale copy)
cp -f /root/.claude/settings.json /home/developer/.claude/settings.json 2>/dev/null || true
for d in agents skills hooks rules; do
  if [ -d "/root/.claude/$d" ]; then
    rm -rf "/home/developer/.claude/$d" 2>/dev/null || true
    mkdir -p "/home/developer/.claude/$d"
    cp -rf "/root/.claude/$d/." "/home/developer/.claude/$d/" 2>/dev/null || true
  fi
done

# Local additions (runtime-generated by documentator). The local/ tree survives
# the resync above. Agents and skills are exposed to Claude Code via symlinks
# into the canonical paths (probe-tested 2026-05-05 — Claude Code follows
# symlinks for agent dispatch). Hooks and rules under local/ are wired through
# settings.local.json with absolute paths, no symlink needed.
LOCAL="/home/developer/.claude/local"
mkdir -p "$LOCAL/agents" "$LOCAL/skills" "$LOCAL/hooks" "$LOCAL/rules"
for kind in agents skills; do
  for src in "$LOCAL/$kind"/*.md; do
    [ -e "$src" ] || continue
    target="/home/developer/.claude/$kind/$(basename "$src")"
    [ -e "$target" ] && continue
    ln -s "$src" "$target"
  done
done

# settings.local.json — Claude Code auto-loads this when present. Survives the
# resync (we never overwrite it). The documentator wires its new hooks here.
if [ ! -f "/home/developer/.claude/settings.local.json" ]; then
  printf '{\n  "hooks": {}\n}\n' > /home/developer/.claude/settings.local.json
fi

# Fix ownership — credentials written during bootstrap run as root
chown -R developer:developer /home/developer/.claude 2>/dev/null || true

# Chat-service logs dir (bind-mounted in dev, needs developer write access)
mkdir -p /chat-service/logs 2>/dev/null || true
chmod 777 /chat-service/logs 2>/dev/null || true
# hooks.log is touched/appended by dozens of subagent processes; ensure it
# exists and is writable by `developer` so a stale root-owned file from a
# previous troubleshooting session doesn't silently break logging.
touch /chat-service/logs/hooks.log 2>/dev/null || true
chown developer:developer /chat-service/logs/hooks.log 2>/dev/null || true
chmod 664 /chat-service/logs/hooks.log 2>/dev/null || true

# Runtime-generated docs (reflections, learnings) — bind-mounted from host ./crm-docs.
# On a fresh host, the directory may be empty and owned by root (if Docker runs as
# root on Linux) or by a host UID that doesn't match developer's UID. Without this
# chown the developer cannot write reflections and Mode 2 silently fails.
# Note: ticket files (TASK-XXX.json) live in /chat-service/logs/<sessionId>/ now,
# alongside log.jsonl and meta.json — chown'd via the chat-service logs block above.
mkdir -p /app/docs/reflections /app/docs/learnings 2>/dev/null || true

if [ ! -f /app/docs/learnings/patterns.md ]; then
  cat > /app/docs/learnings/patterns.md <<'PATTERNS_EOF'
# Patterns ledger

Index of patterns captured by the `documentator` agent. The documentator is
triggered explicitly by the maintainer ("retiens X", "documente Y") — it is
not on a schedule. Each entry points to a runtime artifact under
`/home/developer/.claude/local/{rules,skills,hooks,agents}/`.

---

<!-- Patterns appear below this line. Documentator preserves the file header verbatim. -->
PATTERNS_EOF
fi

chown -R developer:developer /app/docs 2>/dev/null || true

# Worktrees root — lives inside /app so cp -al hard-links against
# /app/node_modules stay on the same device. Excluded from git via .gitignore.
mkdir -p /app/worktrees 2>/dev/null || true
chown -R developer:developer /app/worktrees 2>/dev/null || true

# Make sure /app/worktrees is gitignored (idempotent — only adds the line if
# missing). Without this, `git status` in /app would list every worktree as
# untracked and merger would try to add them.
if [ -f /app/.gitignore ] && ! grep -qxF 'worktrees/' /app/.gitignore; then
  echo 'worktrees/' >> /app/.gitignore
fi

# ── Sync node_modules with package-lock.json ──────────────────
# Volume crm-app:/app persists node_modules across restarts. If an agent
# modifies package.json/package-lock.json (e.g. adds a dependency) and
# commits, the volume keeps the old node_modules. Hash-check at boot:
# if package-lock.json changed since last npm ci, re-install.
LOCK_HASH=$(sha256sum /app/package-lock.json 2>/dev/null | cut -d' ' -f1)
PREV_HASH=$(cat /app/.npm-ci-hash 2>/dev/null || echo "")
if [ -n "$LOCK_HASH" ] && [ "$LOCK_HASH" != "$PREV_HASH" ]; then
  echo -e "${YELLOW}package-lock.json changed → wiping and reinstalling node_modules${NC}"
  # rm -rf is mandatory: npm ci over an existing node_modules occasionally
  # fails with ENOTEMPTY when a transitive dep tree shape changes (e.g.
  # 'rmdir es-abstract' fails because some sub-dir is non-empty).
  rm -rf /app/node_modules
  (cd /app && su developer -c 'npm ci') || echo -e "${RED}npm ci failed — vite/tsc may be broken${NC}"
  echo "$LOCK_HASH" > /app/.npm-ci-hash
  chown developer:developer /app/.npm-ci-hash
fi

# Write /app/CLAUDE.md orientation header. The upstream atomic-crm CLAUDE.md
# is essentially empty (just `@AGENTS.md`) — we prepend a short pointer to
# project-context.json so every Claude Code spawn auto-loads the right
# guidance. Idempotent: regenerated on every boot from this template.
APP_AGENTS_REF=""
if [ -f /app/AGENTS.md ]; then
  APP_AGENTS_REF=$'\n@AGENTS.md\n'
fi
cat > /app/CLAUDE.md <<CLAUDEMD
# Project context

This CRM is configured for the user's specific business. The single source
of truth for entities, fields, pipeline stages, user roles, and integrations
is:

  docs/project-context.json

Read it before adding/modifying any entity or field. The structured spec is
maintained by the \`project-manager\` agent (interview flow). Do not edit it
manually — request a setup via the chat UI's "Define your business" flow.

If the file is missing or has \`validated: false\`, the project has not yet
been cadred — propose the user to run "Define your business" from the chat
UI before implementing entity/field changes.
${APP_AGENTS_REF}
CLAUDEMD
chown developer:developer /app/CLAUDE.md 2>/dev/null || true

# Commit the orientation file on main if it differs from HEAD. Without this
# commit, the merger's `git reset --hard HEAD` (in /app between merges) would
# silently restore the upstream stub. Idempotent: no-op if content matches.
#
# Everything runs as `developer` because `/app` is chown'd to developer above —
# git refuses with "dubious ownership" when run as root.
if [ -d /app/.git ]; then
  su developer -c '
    set -e
    cd /app
    BRANCH=$(git symbolic-ref --short HEAD 2>/dev/null || true)
    if [ -z "$BRANCH" ]; then
      exit 0  # detached HEAD or mid-rebase — skip
    fi
    if git diff --quiet HEAD -- CLAUDE.md 2>/dev/null; then
      exit 0  # already up to date
    fi
    git add CLAUDE.md
    git -c user.name="Atomic CRM Builder" \
        -c user.email="builder@atomic-crm.local" \
        commit -m "chore: refresh CLAUDE.md orientation header" --quiet
  ' || echo -e "${YELLOW}Could not commit CLAUDE.md (non-fatal)${NC}"
fi

# Disable atomic-crm project's PostToolUse format-file.sh hook — replaced by a
# SubagentStop prettier hook in our crm-builder config. The PostToolUse variant
# caused an edit/prettier loop (developer edits → hook reformats → developer
# re-reads different bytes → confusion). The Stop-time hook checks cleanly
# once, fails loudly if not clean, and lets the developer batch-fix with
# `npm run prettier:apply` if needed.
if [ -f /app/.claude/settings.json ]; then
  printf '{\n  "hooks": {}\n}\n' > /app/.claude/settings.json
fi

cd ${APP_DIR}

# ── App.tsx variant helper (called here AND by merger after git reset) ─────
# Extracted to a standalone script so the merger can re-apply it after
# `git reset --hard HEAD` in /app (the reset silently reverts src/App.tsx to
# the tracked upstream form, which has no data provider wiring).
mkdir -p /entrypoint-helpers
cat > /entrypoint-helpers/apply-app-variant.sh <<'HELPER'
#!/bin/bash
# Copy the mode-appropriate App.tsx variant into /app/src/App.tsx.
# Reads MODE from env (default: demo). Idempotent.
set -e
MODE="${MODE:-demo}"
if [ "$MODE" = "full" ]; then
  cp /app-variants/App.supabase.tsx /app/src/App.tsx
else
  cp /app-variants/App.fakerest.tsx /app/src/App.tsx
fi
HELPER
chmod +x /entrypoint-helpers/apply-app-variant.sh

# ── App.tsx variant ───────────────────────────────────────────
/entrypoint-helpers/apply-app-variant.sh
if [ "$MODE" = "demo" ]; then
  echo -e "${GREEN}✓  Data provider: FakeRest${NC}"
else
  echo -e "${GREEN}✓  Data provider: Supabase${NC}"
fi

# ── Docker socket group (enables runtime mode switch to Supabase) ─
if [ -S /var/run/docker.sock ]; then
  DOCKER_GID=$(stat -c '%g' /var/run/docker.sock)
  if ! getent group "$DOCKER_GID" > /dev/null 2>&1; then
    groupadd --gid "$DOCKER_GID" docker-host
  fi
  usermod -aG "$DOCKER_GID" developer
  echo -e "${GREEN}✓  Docker socket available (GID=${DOCKER_GID})${NC}"
fi

# ── Start Supabase when MODE=full ─────────────────────────────
if [ "$MODE" = "full" ]; then
  if [ ! -S /var/run/docker.sock ]; then
    echo ""
    echo -e "${RED}❌  Docker socket not found!${NC}"
    echo "    Full mode requires the Docker daemon."
    echo "    Add: -v /var/run/docker.sock:/var/run/docker.sock"
    echo ""
    echo "    Or use demo mode: MODE=demo docker compose up"
    exit 1
  fi

  echo ""
  echo -e "${BOLD}Starting Supabase...${NC}"
  echo -e "${YELLOW}(First run: ~2 min to pull images)${NC}"
  npx supabase start 2>&1 | grep -E "✓|✗|Error|Started|API URL" || true

  echo -e "${BOLD}Waiting for Supabase API (localhost:54321)...${NC}"
  RETRIES=60
  until curl -s --max-time 2 -o /dev/null http://localhost:54321; do
    RETRIES=$((RETRIES - 1))
    if [ $RETRIES -le 0 ]; then
      echo -e "${RED}❌  Supabase did not respond after 60s${NC}"
      exit 1
    fi
    sleep 1
  done
  echo -e "${GREEN}✓  Supabase ready (localhost:54321)${NC}"
fi

# Commit the App.tsx variant so `git reset --hard HEAD` in the merger restores
# the correct data-provider wiring instead of the upstream stub. Same pattern
# as the CLAUDE.md commit above — idempotent, no-op when content already matches.
if [ -d /app/.git ]; then
  su developer -c '
    set -e
    cd /app
    BRANCH=$(git symbolic-ref --short HEAD 2>/dev/null || true)
    if [ -z "$BRANCH" ]; then
      exit 0  # detached HEAD or mid-rebase — skip
    fi
    if git diff --quiet HEAD -- src/App.tsx 2>/dev/null; then
      exit 0  # already up to date
    fi
    git add src/App.tsx
    git -c user.name="Atomic CRM Builder" \
        -c user.email="builder@atomic-crm.local" \
        commit -m "chore: pin App.tsx to data-provider variant" --quiet
  ' || echo -e "${YELLOW}Could not commit App.tsx (non-fatal)${NC}"
fi

# ── URL summary ───────────────────────────────────────────────
echo ""
echo -e "  ${BLUE}🌐  CRM              →  http://localhost:5173${NC}"
if [ "$MODE" = "full" ]; then
echo -e "  ${BLUE}🗄️   Supabase          →  http://localhost:54323${NC}"
fi
echo -e "  ${BLUE}💬  Chat assistant    →  http://localhost:8080${NC}"
echo -e "  ${BLUE}🤖  Claude terminal   →  http://localhost:7681${NC}"
echo ""
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${YELLOW}  Open http://localhost:7681 and type:                 ${NC}"
echo -e "${YELLOW}  claude --dangerously-skip-permissions                ${NC}"
echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# ── Pre-warm Supabase in background (avoids cold-start delay when switching) ─
if [ "$MODE" = "demo" ] && [ -S /var/run/docker.sock ]; then
  echo -e "${YELLOW}↻  Pre-warming Supabase in background (ready for mode switch)...${NC}"
  (cd /app && npx supabase start > /var/log/supabase-prewarm.log 2>&1) &
fi

exec /usr/bin/supervisord -n -c /etc/supervisor/conf.d/supervisord.conf
