import { createServer } from 'http';
import { join } from 'path';
import { fileURLToPath } from 'url';
import { WebSocketServer } from 'ws';

import { PORT, WELCOME_CHOICES, DOCUMENTATOR_OPTS } from './lib/server/config.js';
import { scheduleDocumentator } from './lib/documentator-cron.js';
import { loadSystemPrompt, applySystemPrompt } from './lib/server/system-prompt.js';
import { openSession } from './lib/server/session-store.js';
import { createRequestHandler } from './lib/server/http-routes.js';
import { runtimes, wsToRuntime, runtimeForWs, createRuntime, safeSend } from './lib/server/runtime.js';
import { sendProgress } from './lib/server/ticket-progress.js';
import { regenerateTitleWithHaiku, extractText, extractToolUses } from './lib/server/claude-spawn.js';
import { processMessage } from './lib/server/turn.js';
import { endsWithQuestion } from './lib/server/session-store.js';

// Re-exported for unit tests (test/server.test.js imports from '../server.js').
export { extractText, extractToolUses, endsWithQuestion };

const __dirname = fileURLToPath(new URL('.', import.meta.url));

const httpServer = createServer(createRequestHandler({ publicDir: join(__dirname, 'public') }));

const wss = new WebSocketServer({ server: httpServer });
wss.on('error', (err) => console.error('WebSocket server error:', err));
httpServer.on('error', (err) => console.error('HTTP server error:', err));

wss.on('connection', async (ws, req) => {
  const urlObj = new URL(req.url || '/', `http://${req.headers.host || 'localhost'}`);
  const requestedId = urlObj.searchParams.get('session');
  const session = await openSession(requestedId).catch(() => null);
  if (!session) {
    ws.close();
    return;
  }

  let runtime = runtimes.get(session.id);
  const joining = !!runtime;
  // `session.messages` holds a fresh snapshot read just now from the log —
  // always send these on init (the runtime's own `session.messages` would
  // be the stale snapshot from when the runtime was first opened).
  const freshMessages = session.messages;
  if (!runtime) {
    runtime = createRuntime(session);
    runtimes.set(session.id, runtime);
  } else {
    // Another tab/reconnect is joining an existing runtime. Discard the
    // newly-opened session handle (it would duplicate the log stream);
    // the runtime keeps the original.
    session.close();
  }
  runtime.clients.add(ws);
  wsToRuntime.set(ws, runtime.session.id);
  console.log(`Session ${session.isNew ? 'created' : joining ? 'rejoined' : 'resumed'}: ${runtime.session.id}`);

  safeSend(ws, {
    type: 'init',
    sessionId: runtime.session.id,
    title: runtime.session.meta.title,
    state: runtime.session.meta.state || 'in_progress',
    messages: freshMessages,
    // Messages currently waiting in the queue are persisted in the log like
    // any other user message; the "waiting" badge is a pure client-side
    // marker. Tell the joining tab how many of the tail user messages are
    // still queued so it can re-apply the badge.
    queuedCount: runtime.queue.length,
    // Re-hydrate the "working" UI (dots, stop button, spinner) when a turn
    // is in progress — conveyed inline rather than via a separate status
    // frame so the client doesn't mistakenly interpret it as a false→true
    // transition (which would demote a still-queued message).
    working: runtime.busy,
    isNew: session.isNew,
  });
  if (session.isNew) {
    safeSend(ws, WELCOME_CHOICES);
  }
  // Send the current progress snapshot so a (re)joining tab paints the
  // counter immediately instead of waiting for the next merge / write event.
  sendProgress(runtime).catch(() => {});

  ws.on('message', (data) => {
    let parsed;
    try { parsed = JSON.parse(data.toString()); } catch { return; }

    const r = runtimeForWs(ws);
    if (!r) return;

    // Stop button: kill the running claude process and clear the queue.
    if (parsed.type === 'stop') {
      if (!r.busy) return;
      r.stopping = true;
      r.queue = [];
      const p = r.currentProc;
      if (p && !p.killed) {
        try { p.kill('SIGTERM'); } catch {}
        setTimeout(() => {
          try { if (p && !p.killed) p.kill('SIGKILL'); } catch {}
        }, 2000);
      }
      r.session?.logWrite('in', { type: 'stop_requested' });
      return;
    }

    if (!parsed.content?.trim()) return;
    // `display` is an optional client-side label (e.g. for choice buttons) —
    // what the user actually saw. `content` is what we forward to claude.
    const displayed = typeof parsed.display === 'string' && parsed.display.trim()
      ? parsed.display
      : parsed.content;
    r.session.logWrite('in', { type: 'user_message', content: parsed.content, display: displayed });
    r.session.recordMessage('user', displayed).then(() => {
      // Trigger Haiku retitling on the 2nd user message, once per session.
      const m = r.session.meta;
      if (m.userMessageCount === 2 && !m.titleLocked && !m.titleAutoGenerated) {
        regenerateTitleWithHaiku(r).catch(() => {});
      }
    }).catch(() => {});
    if (r.busy) {
      r.queue.push(parsed.content);
    } else {
      r.busy = true;
      processMessage(r, parsed.content);
    }
  });

  ws.on('close', () => {
    const r = runtimeForWs(ws);
    wsToRuntime.delete(ws);
    if (!r) return;
    r.clients.delete(ws);
    // Only tear down when the session is fully idle. If a turn is still
    // running, processMessage's finally block will release the runtime once
    // it finishes (if no clients are left by then).
    if (r.clients.size === 0 && !r.busy) {
      r.session?.close();
      runtimes.delete(r.session.id);
    }
  });
});

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  loadSystemPrompt().then((parsed) => {
    applySystemPrompt(parsed);
    const t = parsed.tools?.length ? parsed.tools.join(',') : 'default';
    console.log(parsed.content ? `Orchestrator loaded (model: ${parsed.model || 'default'}, tools: ${t}).` : 'No orchestrator prompt, using default.');
  });
  scheduleDocumentator(DOCUMENTATOR_OPTS);
  httpServer.listen(PORT, '0.0.0.0', () => {
    console.log(`Chat service listening on port ${PORT}`);
  });
}
