#!/usr/bin/env node
// Migrate an old-format chat-logs/session-<iso>.jsonl into a new-format sessions/<uuid>/ pair.
// Usage: node scripts/migrate-old-log.mjs <path-to-old-log.jsonl> [--out <sessions-dir>]

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { basename, join, resolve } from 'node:path';

const args = process.argv.slice(2);
if (args.length < 1) {
  console.error('Usage: migrate-old-log.mjs <old-log.jsonl> [--out <sessions-dir>]');
  process.exit(2);
}
const src = resolve(args[0]);
const outIdx = args.indexOf('--out');
const sessionsDir = resolve(outIdx >= 0 ? args[outIdx + 1] : join(process.cwd(), 'sessions'));

const raw = await readFile(src, 'utf8');
const lines = raw.split('\n').filter(Boolean);

let claudeSessionId = null;
let firstTs = null;
let lastTs = null;
let lastMessageTs = null;
let userMsgCount = 0;
let msgCount = 0;
let titleContent = '';
// The old log format sent choice-button clicks as raw IDs (FULL_SETUP / QUICK_EDIT)
// without a `display` field. Those IDs make terrible titles, so skip them and take
// the first real free-text message instead.
const CHOICE_IDS = new Set(['FULL_SETUP', 'QUICK_EDIT']);

for (const line of lines) {
  let rec;
  try { rec = JSON.parse(line); } catch { continue; }
  if (rec.ts) { firstTs = firstTs ?? rec.ts; lastTs = rec.ts; }

  if (rec.dir === 'in' && rec.type === 'user_message') {
    userMsgCount++; msgCount++; lastMessageTs = rec.ts;
    const content = rec.display || rec.content || '';
    if (!titleContent && !CHOICE_IDS.has(content.trim())) titleContent = content;
  } else if (rec.dir === 'out' && rec.type === 'message' && rec.role === 'assistant') {
    msgCount++; lastMessageTs = rec.ts;
  } else if (rec.dir === 'out' && rec.type === 'debug_raw' && rec.event?.session_id && !claudeSessionId) {
    claudeSessionId = rec.event.session_id;
  }
}

const id = randomUUID();
const title = titleContent.trim().replace(/\s+/g, ' ').slice(0, 60);
const meta = {
  id,
  title,
  state: 'completed',
  createdAt: firstTs,
  lastMessageAt: lastMessageTs ?? lastTs,
  messageCount: msgCount,
  claudeSessionId,
  userMessageCount: userMsgCount,
  titleAutoGenerated: true,
  migratedFrom: basename(src),
};

const destDir = join(sessionsDir, id);
await mkdir(destDir, { recursive: true });
// Strip the old `session_meta` event type (no longer emitted by the server) but keep everything else.
const migratedLog = lines
  .filter((l) => {
    try { const r = JSON.parse(l); return r.type !== 'session_meta'; } catch { return false; }
  })
  .join('\n') + '\n';
await writeFile(join(destDir, 'log.jsonl'), migratedLog);
await writeFile(join(destDir, 'meta.json'), JSON.stringify(meta, null, 2));
console.log(`✓ migrated → ${destDir}`);
console.log(`  title: ${title}`);
console.log(`  messages: ${msgCount} (user: ${userMsgCount})`);
console.log(`  range: ${firstTs} → ${lastTs}`);
