import { spawn } from 'node:child_process';
import { CWD, CLAUDE_HOME } from './config.js';
import { getSystemPrompt, getOrchestratorModel } from './system-prompt.js';
import { broadcast } from './ws-bus.js';
import { readMessages } from './session-store.js';
import { buildSpawnEnv } from '../spawn-env.js';

// Exported for unit testing
export function extractText(msg) {
  if (msg.type !== 'assistant') return null;
  const blocks = msg.message?.content;
  if (!Array.isArray(blocks)) return null;
  const text = blocks
    .filter((b) => b.type === 'text')
    .map((b) => b.text)
    .join('');
  return text.trim() ? text : null;
}

export function extractToolUses(msg) {
  if (msg.type !== 'assistant') return [];
  const blocks = msg.message?.content;
  if (!Array.isArray(blocks)) return [];
  return blocks.filter((b) => b.type === 'tool_use');
}

// The chat UI's "Define your business" button sends `content: 'FULL_SETUP'`.
// We rewrite it into an explicit `<intent>setup</intent>` marker the
// orchestrator recognises (cohérent with `<mode>` / `<session_dir>` env tags).
// Plain-text fallback is kept so any NL detection in the orchestrator still
// has something to chew on.
export function rewriteUserMessage(userMessage) {
  if (userMessage === 'FULL_SETUP') {
    return '<intent>setup</intent>\nUser clicked "Define your business" — start the project setup interview.';
  }
  return userMessage;
}

export function spawnClaude(userMessage, claudeSessionId, sessionDir) {
  const mode = process.env.MODE || 'demo';
  const env = `<mode>${mode}</mode>\n<session_dir>${sessionDir}</session_dir>`;
  const systemPrompt = getSystemPrompt();
  const orchestratorModel = getOrchestratorModel();
  const finalUserMessage = rewriteUserMessage(userMessage);
  const prompt = systemPrompt
    ? `<instructions>\n${systemPrompt}\n</instructions>\n\n${env}\n\n${finalUserMessage}`
    : `${env}\n\n${finalUserMessage}`;
  const args = [
    '--output-format', 'stream-json',
    '--verbose',
    '--dangerously-skip-permissions',
    // The orchestrator never calls MCP tools directly — it routes via Agent/Teams.
    // Loading 13+ claude.ai "needs-auth" servers wastes ~8K tokens per spawn.
    '--strict-mcp-config', '--mcp-config', '{"mcpServers":{}}',
  ];
  if (orchestratorModel) args.push('--model', orchestratorModel);
  if (claudeSessionId) args.push('--resume', claudeSessionId);
  args.push('-p', prompt);
  return spawn('claude', args, {
    env: buildSpawnEnv({
      ...process.env,
      HOME: CLAUDE_HOME,
      CLAUDE_PROJECT_DIR: CWD,
      CHAT_SESSION_DIR: sessionDir,
      MODE: mode,
    }, claudeSessionId),
    cwd: CWD,
    stdio: ['ignore', 'pipe', 'pipe'],
  });
}

// Runs a one-shot Haiku call to regenerate the session title. Invoked when
// the user sends their 1st message so the label reflects what the chat is
// actually about (the initial auto-title is a crude first-message slice).
export async function regenerateTitleWithHaiku(runtime) {
  const session = runtime?.session;
  if (!session) return;
  const m = session.meta;
  if (m.titleLocked || m.titleAutoGenerated) return;

  const msgs = await readMessages(session.id);
  if (msgs.length < 1) return;

  // Send the first few exchanges — more than that dilutes the signal.
  const convo = msgs.slice(0, 6)
    .map((x) => `${x.role === 'user' ? 'User' : 'Assistant'}: ${x.content}`)
    .join('\n\n');
  const prompt =
    `Based on the conversation below, generate a concise title (3 to 6 words, ` +
    `same language as the user, no punctuation, no quotes, no emoji). ` +
    `Reply with ONLY the title, nothing else.\n\n${convo}`;

  const proc = spawn('claude', [
    '--model', 'claude-haiku-4-5',
    '--dangerously-skip-permissions',
    '-p', prompt,
  ], {
    env: { ...process.env, HOME: CLAUDE_HOME },
    cwd: CWD,
    stdio: ['ignore', 'pipe', 'pipe'],
  });
  proc.once('error', () => {}); // Don't crash if claude isn't on PATH.

  let out = '';
  let err = '';
  proc.stdout.on('data', (d) => { out += d.toString(); });
  proc.stderr.on('data', (d) => { err += d.toString(); });
  const exitCode = await new Promise((resolve) => proc.once('close', resolve))
    .catch(() => -1);
  if (exitCode !== 0) {
    if (err) console.error('[haiku-title]', err.trim());
    return;
  }

  const title = out.trim().split('\n')[0]
    .replace(/^["'`«]+|["'`»]+$/g, '')
    .replace(/\s+/g, ' ')
    .slice(0, 100);
  if (!title) return;

  // Re-check the flag — the user could have renamed while Haiku was running.
  if (session.meta.titleLocked) return;
  await session.setTitle(title, { auto: true });
  broadcast(runtime, { type: 'title', title });
}

export function friendlyError({ exitCode, stderr, rateLimit, resultError }) {
  if (rateLimit?.resetsAt) {
    const minutes = Math.max(1, Math.ceil((rateLimit.resetsAt * 1000 - Date.now()) / 60000));
    return `Usage limit reached. You can try again in about ${minutes} minute(s).`;
  }
  if (/invalid[_ ]api[_ ]key|authentication|unauthori[sz]ed|401/i.test(stderr)) {
    return "Access has expired. Please contact your administrator to renew the session.";
  }
  if (/network|ECONNREFUSED|ENOTFOUND|ETIMEDOUT/i.test(stderr)) {
    return "Unable to reach the service right now. Check your connection and try again.";
  }
  if (resultError) {
    return "Something went wrong while processing your request. Want to try again?";
  }
  if (exitCode !== 0) {
    return "An unexpected error occurred. Want to try again?";
  }
  return "I couldn't complete your request. Could you rephrase it?";
}
