import { readFile, writeFile, mkdir, readdir } from 'node:fs/promises';
import { createWriteStream } from 'node:fs';
import { randomUUID } from 'node:crypto';
import { LOG_DIR, UUID_RE, ALLOWED_STATES } from './config.js';

// ─── Session persistence ──────────────────────────────────────
// Single source of truth = log.jsonl (append-only stream of ws in/out events).
// meta.json holds only lightweight metadata (title, timestamps, counts,
// claudeSessionId) so the listing page doesn't have to parse every log.
// Visible messages (user + assistant) are derived from log.jsonl on demand.

function digestLog(logText) {
  const messages = [];
  let tokensUsed = 0;
  let costUsd = 0;
  for (const line of logText.split('\n')) {
    if (!line) continue;
    let entry;
    try { entry = JSON.parse(line); } catch { continue; }
    if (entry.dir === 'in' && entry.type === 'user_message') {
      messages.push({ role: 'user', content: entry.display || entry.content || '', ts: entry.ts });
    } else if (entry.dir === 'out' && entry.type === 'message' && entry.role === 'assistant') {
      messages.push({ role: 'assistant', content: entry.content || '', ts: entry.ts });
    } else if (entry.dir === 'out' && entry.type === 'debug_raw' && entry.event?.type === 'result') {
      // Each result event is end-of-spawn; total_cost_usd is the cumulative cost
      // for that spawn, so summing per-result is correct (one result per spawn).
      const u = entry.event.usage || {};
      tokensUsed += (u.input_tokens || 0) + (u.cache_creation_input_tokens || 0) + (u.output_tokens || 0);
      costUsd += entry.event.total_cost_usd || 0;
    }
  }
  return { messages, stats: { tokensUsed, costUsd } };
}

export async function readDigest(id) {
  try {
    const raw = await readFile(`${LOG_DIR}/${id}/log.jsonl`, 'utf8');
    return digestLog(raw);
  } catch {
    return { messages: [], stats: { tokensUsed: 0, costUsd: 0 } };
  }
}

export async function readMessages(id) {
  return (await readDigest(id)).messages;
}

export async function openSession(requestedId) {
  await mkdir(LOG_DIR, { recursive: true }).catch(() => {});
  let id = requestedId && UUID_RE.test(requestedId) ? requestedId : null;
  let meta = null;
  let isNew = false;
  let messages = [];
  let stats = { tokensUsed: 0, costUsd: 0 };

  if (id) {
    try {
      meta = JSON.parse(await readFile(`${LOG_DIR}/${id}/meta.json`, 'utf8'));
      const digest = await readDigest(id);
      messages = digest.messages;
      stats = digest.stats;
    } catch {
      id = null;
      meta = null;
    }
  }

  if (!id) {
    id = randomUUID();
    isNew = true;
    await mkdir(`${LOG_DIR}/${id}`, { recursive: true });
    meta = {
      id,
      title: '',
      state: 'in_progress',
      createdAt: new Date().toISOString(),
      lastMessageAt: null,
      messageCount: 0,
      claudeSessionId: null,
    };
    await writeFile(`${LOG_DIR}/${id}/meta.json`, JSON.stringify(meta, null, 2));
  }

  const logStream = createWriteStream(`${LOG_DIR}/${id}/log.jsonl`, { flags: 'a' });

  const saveMeta = () =>
    writeFile(`${LOG_DIR}/${id}/meta.json`, JSON.stringify(meta, null, 2));

  return {
    id,
    isNew,
    get meta() { return meta; },
    messages,
    // Cumulative tokens/cost reconstructed from the log so the inline ticker
    // survives a runtime teardown (last tab closed) and a page refresh.
    stats,
    logWrite: (dir, data) =>
      logStream.write(JSON.stringify({ ts: new Date().toISOString(), dir, ...data }) + '\n'),
    // Record that a visible message has just been appended to the log (meta side effects only).
    recordMessage: async (role, content) => {
      meta.lastMessageAt = new Date().toISOString();
      meta.messageCount = (meta.messageCount || 0) + 1;
      if (role === 'user') {
        meta.userMessageCount = (meta.userMessageCount || 0) + 1;
        if (!meta.title) meta.title = content.trim().replace(/\s+/g, ' ').slice(0, 60);
      }
      await saveMeta();
    },
    setTitle: async (newTitle, { auto = false } = {}) => {
      meta.title = newTitle;
      if (auto) meta.titleAutoGenerated = true;
      await saveMeta();
    },
    setClaudeSessionId: async (csid) => {
      if (!csid || meta.claudeSessionId === csid) return;
      meta.claudeSessionId = csid;
      await saveMeta();
    },
    setState: async (newState) => {
      if (!ALLOWED_STATES.has(newState) || meta.state === newState) return false;
      meta.state = newState;
      await saveMeta();
      return true;
    },
    // In-memory equivalent of patchSession — keeps the runtime's meta object
    // in sync when an HTTP PATCH lands on a session that's currently active.
    // Without this, a subsequent saveMeta() from the running turn would
    // overwrite the user's change with stale data.
    applyPatch: async (patch) => {
      applyMetaPatch(meta, patch);
      await saveMeta();
      return meta;
    },
    close: () => logStream.end(),
  };
}

function applyMetaPatch(meta, patch) {
  if (typeof patch.title === 'string') {
    meta.title = patch.title.slice(0, 200);
    meta.titleLocked = true;
  }
  if (typeof patch.state === 'string' && ALLOWED_STATES.has(patch.state)) {
    meta.state = patch.state;
  }
}

// Heuristic: Claude's final message ends with a question → session is waiting
// for a user reply (e.g. "Quelle couleur préférez-vous ?"). We look at the last
// non-empty paragraph so a mid-message question followed by a conclusion does
// not trigger; a question followed by a trailing code block still falls
// through to 'completed' since the code block becomes the last paragraph.
// Exported for unit testing.
export function endsWithQuestion(text) {
  if (!text) return false;
  const paragraphs = text.split(/\n\s*\n/).map((p) => p.trim()).filter(Boolean);
  const lastPara = paragraphs[paragraphs.length - 1] || '';
  const trimmed = lastPara.replace(/[\s)\]*_`'"]+$/, '');
  return trimmed.endsWith('?');
}

export async function listSessions() {
  await mkdir(LOG_DIR, { recursive: true }).catch(() => {});
  const entries = await readdir(LOG_DIR, { withFileTypes: true }).catch(() => []);
  const out = [];
  for (const entry of entries) {
    if (!entry.isDirectory() || !UUID_RE.test(entry.name)) continue;
    try {
      const meta = JSON.parse(await readFile(`${LOG_DIR}/${entry.name}/meta.json`, 'utf8'));
      const count = meta.messageCount || 0;
      if (count === 0) continue;
      out.push({
        id: meta.id,
        title: meta.title || '',
        state: meta.state || 'in_progress',
        createdAt: meta.createdAt,
        lastMessageAt: meta.lastMessageAt,
        messageCount: count,
      });
    } catch {}
  }
  out.sort((a, b) =>
    (b.lastMessageAt || b.createdAt || '').localeCompare(a.lastMessageAt || a.createdAt || '')
  );
  return out;
}

export async function getSession(id) {
  if (!UUID_RE.test(id)) return null;
  try {
    const meta = JSON.parse(await readFile(`${LOG_DIR}/${id}/meta.json`, 'utf8'));
    const messages = await readMessages(id);
    return { meta, messages };
  } catch {
    return null;
  }
}

export async function patchSession(id, patch) {
  if (!UUID_RE.test(id)) return null;
  try {
    const path = `${LOG_DIR}/${id}/meta.json`;
    const meta = JSON.parse(await readFile(path, 'utf8'));
    applyMetaPatch(meta, patch);
    await writeFile(path, JSON.stringify(meta, null, 2));
    return meta;
  } catch {
    return null;
  }
}
